### ISSUE TITLE
direct link via github pages or rawgit

### ISSUE THREAD

**Issue by cben** [OscarBarrett/MobyDock-Lego#1]
Thanks for the instructions! :building_construction: :whale: 

For easier browsing of instructions without need to clone, you can either:

1. Link to rawgit: https://rawgit.com/OscarBarrett/MobyDock-Lego/master/Building%20Instructions%20%5BMoby%20Dock%5D.html

2. Enable Github Pages in repo settings, from master branch:
  (forked and tested: https://cben.github.io/MobyDock-Lego/Building%20Instructions%20%5BMoby%20Dock%5D.html)

**Comment by OscarBarrett** [comment]
Thanks! I've enabled GitHub Pages and linked to the instruction in the readme.
